name: 二进制构建

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest 
    name: Build
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Publish
      run: dotnet publish -c Release -f net10.0-windows10.0.19041.0 -r win-x64 --self-contained false -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ICC-DN10
        path: publish
