name: 发行版

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest 
    name: Build
    
    steps:
    - name: 初始化
      uses: actions/checkout@v4

    - name: 安装 .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: 生成二进制文件
      run: dotnet publish -c Release -f net10.0-windows10.0.19041.0 -r win-x64 --self-contained true -o publish

    - name: 上传二进制文件
      uses: actions/upload-artifact@v4
      with:
        name: ICC-DN10-Release
        path: publish
